on:
  push:
    branches: ["main", "stg"]

name: 🚀 CNAD

jobs:
  set-environment:
    name: Set Environment
    runs-on: ubuntu-latest

    outputs:
      ENV: ${{ steps.set-env.outputs.ENV }}

    steps:
      - name: Set environment based on branch
        id: set-env
        run: |
          if [[ ${{ github.ref_name }}  == 'main' ]]; then
            echo "::set-output name=ENV::prod"
          elif [[ ${{ github.ref_name }}  == 'stg' ]]; then
            echo "::set-output name=ENV::stg"
          else
            echo "::set-output name=ENV::"
          fi

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [set-environment]
    environment: ${{ needs.set-environment.outputs.ENV }}
    env:
      NODE_DIR: ${{ secrets.NODE_DIR }}
      RESTART_FILE_PATH: ${{ secrets.RESTART_FILE_PATH }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Generate build
        run: npm run build

      - name: List files recursively
        run: find . -path ./node_modules -prune -o -type f -print

      - name: Upload .next folder
        uses: actions/upload-artifact@v4
        with:
          name: dot_next_folder
          path: .next/

  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    needs: [build, set-environment]
    environment: ${{ needs.set-environment.outputs.ENV }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Creating restart file
        run: |
          mkdir tmp && touch tmp/restart.txt
          echo $RANDOM > tmp/restart.txt

      - name: download .next folder
        uses: actions/download-artifact@v4
        with:
          name: dot_next_folder
          path: .next

      - name: Debugging environments
        run: |
          echo "FTP_HOST ${{ secrets.FTP_HOST }}"
          echo "FTP_PASSWORD ${{ secrets.FTP_PASSWORD }}"
          echo "FTP_USER ${{ secrets.FTP_USER }}"

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/.next/cache/**
            **/.github/**
            **/.git/**
            **/pages/**
            **/css/**
            **/layouts/**
            **/components/**
            **/lib/**
            **/sitedata/**
            **/postcss.config.js
            **/tailwind.config.js
            **/README.md
            **/.gitignore
            **/.eslintrc.json
