on:
  push:
    branches: ["main", "stg"]

name: 🚀 CNAD

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      NODE_DIR: ${{ secrets.NODE_DIR }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: $NODE_DIR ci

      - name: Generate build
        run: $NODE_DIR run build

      - name: Upload .next folder
        uses: actions/upload-artifact@v4
        with:
          name: dot_next_folder
          path: .next/

  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Creating restart file
        run: |
          mkdir tmp && touch tmp/restart.txt
          echo $RANDOM > tmp/restart.txt

      - name: download .next folder
        uses: actions/download-artifact@v3
        with:
          name: dot_next_folder
          path: .next

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/.next/cache/**
            **/.github/**
            **/.git/**
            **/pages/**
            **/css/**
            **/layouts/**
            **/components/**
            **/lib/**
            **/sitedata/**
            **/postcss.config.js
            **/tailwind.config.js
            **/README.md
            **/.gitignore
            **/.eslintrc.json
