on:
  push:
    branches: ["main", "stg"]

name: 🚀 CNAD

jobs:
  set-environment:
    name: Set Environment
    runs-on: ubuntu-latest

    outputs:
      ENV: ${{ steps.set-env.outputs.ENV }}

    steps:
      - name: Set environment based on branch
        id: set-env
        run: |
          if [[ ${{ github.ref_name }}  == 'main' ]]; then
            echo "ENV=prod" >> "$GITHUB_OUTPUT"
            elif [[ ${{ github.ref_name }}  == 'stg' ]]; then
            echo "ENV=stg" >> "$GITHUB_OUTPUT"
            else
            echo "Invalid environment." || exit 1
          fi

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [set-environment]
    environment: ${{ needs.set-environment.outputs.ENV }}
    env:
      NODE_DIR: ${{ secrets.NODE_DIR }};
      ALLOWED_ORIGIN: ${{ secrets.ALLOWED_ORIGIN }}
      RESTART_FILE_PATH: ${{ secrets.RESTART_FILE_PATH }}
      WP_DOMAIN: ${{ secrets.WP_DOMAIN }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Generate build
        run: npm run build

      - name: List files recursively
        run: find . -path ./node_modules -prune -o -type f -print

      - name: Upload .next folder
        uses: actions/upload-artifact@v4
        with:
          name: dot_next_folder
          path: .next/

  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    needs: [build, set-environment]
    environment: ${{ needs.set-environment.outputs.ENV }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Creating restart file
        run: |
          mkdir tmp && touch tmp/restart.txt
          echo $RANDOM > tmp/restart.txt

      - name: download .next folder
        uses: actions/download-artifact@v4
        with:
          name: dot_next_folder
          run-id: ${{ github.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: .next

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          exclude: |
            **/.next/cache/**
            **/.github/**
            **/.git/**
            pages/**
            css/**
            layouts/**
            components/**
            lib/**
            sitedata/**
            postcss.config.js
            tailwind.config.js
            README.md
            .gitignore
            .eslintrc.json
